<?php
require_once __DIR__.'/../app/bootstrap.php'; require_login();
$type=$_GET['type']??'albums';
$allowed=['albums','artists','genres','languages']; if(!in_array($type,$allowed,true))$type='albums';
$title=ucfirst($type);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($title)?> — Music Admin</title><link rel="stylesheet" href="assets/app.css"></head><body>
<?php include __DIR__.'/partials/sidebar.php'; ?><main class="main"><header class="topbar"><div><h1><?=h($title)?></h1><p class="muted">Manage <?=h($type)?> through the API.</p></div><?php if($type!=='languages'):?><button class="btn primary" onclick="openForm()">+ Add <?=rtrim($title,'s')?></button><?php endif;?></header>
<div id="toast"></div><section class="panel"><div class="toolbar"><input id="search" placeholder="Search…"><button class="btn ghost" onclick="load(1)">Search</button></div><div class="table-wrap"><table><thead id="head"></thead><tbody id="rows"></tbody></table></div><div class="pager" id="pager"></div></section></main>
<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2 id="modalTitle">Add</h2><button onclick="closeModal()">×</button></div><form id="form"></form></div></div>
<script src="assets/app.js"></script><script>
const TYPE=<?=json_encode($type)?>;let page=1,editing=null;
const schemas={albums:[['title','Title','text'],['slug','Slug','text'],['description','Description','textarea'],['cover_url','Cover URL','text'],['release_date','Release date','date'],['album_type','Album type','text'],['copyright','Copyright','text'],['label','Label','text']],artists:[['name','Name','text'],['slug','Slug','text'],['bio','Bio','textarea'],['country','Country','text'],['image_url','Image URL','text'],['verified','Verified','number'],['monthly_listeners','Monthly listeners','number']],genres:[['name','Name','text'],['slug','Slug','text']]};
function renderHead(){ $('head').innerHTML=TYPE==='albums'?'<tr><th>Title</th><th>Type</th><th>Release</th><th>Tracks</th><th></th></tr>':TYPE==='artists'?'<tr><th>Name</th><th>Country</th><th>Listeners</th><th>Verified</th><th></th></tr>':TYPE==='genres'?'<tr><th>Name</th><th>Slug</th><th></th></tr>':'<tr><th>Language</th><th>Songs</th><th></th></tr>'}
async function load(p=1){page=p;let path='/'+TYPE+'?page='+p+'&limit=25'+(($('search').value||'').trim()?'&search='+encodeURIComponent($('search').value.trim()):'');let r=await api(path);if(!r.success)return toast(r.message,'danger');let items=TYPE==='languages'?(r.data||[]):(r.data.items||[]);$('rows').innerHTML=items.map(x=>row(x)).join('')||emptyRow(TYPE==='languages'?3:5,'No records found');let pg=r.data.pagination||{};$('pager').innerHTML=TYPE==='languages'?`<span>${items.length} languages</span>`:`<span>${pg.total||0} records</span><div>${page>1?`<button class="btn ghost" onclick="load(${page-1})">Previous</button>`:''} ${page<(pg.pages||0)?`<button class="btn ghost" onclick="load(${page+1})">Next</button>`:''}</div>`}
function row(x){if(TYPE==='albums')return `<tr><td><b>${esc(x.title)}</b></td><td>${esc(x.album_type||'—')}</td><td>${esc(x.release_date||'—')}</td><td>${x.total_tracks??0}</td><td class="right"><button class="iconbtn" onclick="edit(${x.id})">Edit</button> <button class="iconbtn dangerText" onclick="del(${x.id})">Delete</button></td></tr>`;if(TYPE==='artists')return `<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.country||'—')}</td><td>${Number(x.monthly_listeners||0).toLocaleString()}</td><td>${x.verified?'Yes':'No'}</td><td class="right"><button class="iconbtn" onclick="edit(${x.id})">Edit</button> <button class="iconbtn dangerText" onclick="del(${x.id})">Delete</button></td></tr>`;if(TYPE==='genres')return `<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.slug||'')}</td><td class="right"><button class="iconbtn" onclick="edit(${x.id})">Edit</button> <button class="iconbtn dangerText" onclick="del(${x.id})">Delete</button></td></tr>`;return `<tr><td><b>${esc(x.language)}</b></td><td>${x.song_count}</td><td class="right"><button class="iconbtn" onclick="renameLang(${JSON.stringify(x.language)})">Rename</button></td></tr>`}
function openForm(){editing=null;$('modalTitle').textContent='Add '+TYPE.slice(0,-1);$('form').innerHTML=schemas[TYPE].map(([k,l,t])=>`<label>${l}${t==='textarea'?'<textarea id="f_'+k+'"></textarea>':`<input id="f_${k}" type="${t}">`}</label>`).join('')+'<div class="actions"><button type="button" class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn primary">Save</button></div>';$('modal').classList.add('show')}
async function edit(id){let r=await api('/'+TYPE+'/'+id);if(!r.success)return toast(r.message,'danger');editing=id;openForm();$('modalTitle').textContent='Edit '+TYPE.slice(0,-1);for(const [k] of schemas[TYPE])if(r.data[k]!==undefined)$('f_'+k).value=r.data[k]??''}
$('form').onsubmit=async e=>{e.preventDefault();let body={};for(const [k,,t] of schemas[TYPE])body[k]=t==='number'?Number($('f_'+k).value||0):$('f_'+k).value;let r=await api('/'+TYPE+(editing?'/'+editing:''),editing?'PUT':'POST',body);if(r.success){closeModal();toast('Saved successfully','success');load(page)}else toast(r.message,'danger')};
async function del(id){if(!confirm('Delete this record?'))return;let r=await api('/'+TYPE+'/'+id,'DELETE');toast(r.message,r.success?'success':'danger');if(r.success)load(page)}
async function renameLang(from){let to=prompt('Rename language "'+from+'" to:');if(!to)return;let r=await api('/languages/rename','POST',{from,to});toast(r.message,r.success?'success':'danger');if(r.success)load()}
renderHead();load();
</script></body></html>
