<?php require_once __DIR__.'/../app/bootstrap.php'; require_login(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Songs — Music Admin</title><link rel="stylesheet" href="assets/app.css"></head><body>
<?php include __DIR__.'/partials/sidebar.php'; ?><main class="main"><header class="topbar"><div><h1>Songs</h1><p class="muted">Create, edit and delete songs.</p></div><button class="btn primary" onclick="openSong()">+ Add song</button></header>
<div id="toast"></div><section class="panel"><div class="toolbar"><input id="search" placeholder="Search by song title…"><button class="btn ghost" onclick="load(1)">Search</button></div>
<div class="table-wrap"><table><thead><tr><th>Title</th><th>Language</th><th>Duration</th><th>Plays</th><th>Status</th><th></th></tr></thead><tbody id="rows"></tbody></table></div><div class="pager" id="pager"></div></section></main>
<div class="modal" id="modal"><div class="modal-box wide"><div class="modal-head"><h2 id="mtitle">Add song</h2><button onclick="closeModal()">×</button></div>
<form id="form" class="grid2">
<input type="hidden" id="id"><label>Title<input id="title" required></label><label>Slug<input id="slug" placeholder="Auto-generated"></label>
<label>Audio URL<input id="audio_url" required></label><label>Cover URL<input id="cover_url"></label>
<label>Duration (seconds)<input id="duration_seconds" type="number" min="0" required></label><label>Language<input id="language"></label>
<label>Release date<input id="release_date" type="date"></label><label>Description<textarea id="description"></textarea></label>
<label>Lyrics<textarea id="lyrics"></textarea></label><label>Active<select id="is_active"><option value="1">Yes</option><option value="0">No</option></select></label>
<label>Explicit<select id="is_explicit"><option value="0">No</option><option value="1">Yes</option></select></label>
<div class="full-row"><h3>Relationships</h3><p class="muted">Enter IDs separated by commas. Artist role can be added as <code>12:Featured</code>.</p>
<label>Artist IDs<input id="artists" placeholder="1, 5, 12:Featured"></label><label>Genre IDs<input id="genres" placeholder="2, 4"></label>
<label>Album IDs<input id="albums" placeholder="3"></label></div>
<div class="actions full-row"><button type="button" class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn primary">Save song</button></div>
</form></div></div>
<script src="assets/app.js"></script><script>
let page=1; const $=id=>document.getElementById(id);
async function load(p=1){page=p; const q=$('search').value.trim(); let r=await api('/songs?page='+p+'&limit=25'+(q?'&search='+encodeURIComponent(q):'')); if(!r.success)return toast(r.message,'danger'); $('rows').innerHTML=(r.data.items||[]).map(s=>`<tr><td><b>${esc(s.title)}</b><small>${esc(s.slug||'')}</small></td><td>${esc(s.language||'—')}</td><td>${fmt(s.duration_seconds)}</td><td>${Number(s.play_count||0).toLocaleString()}</td><td>${s.is_active?'Active':'Inactive'}</td><td class="right"><button class="iconbtn" onclick="editSong(${s.id})">Edit</button> <button class="iconbtn dangerText" onclick="delSong(${s.id})">Delete</button></td></tr>`).join('')||emptyRow(6,'No songs found'); const x=r.data.pagination||{}; $('pager').innerHTML=`<span>${x.total||0} songs</span><div>${page>1?`<button class="btn ghost" onclick="load(${page-1})">Previous</button>`:''} ${page<(x.pages||0)?`<button class="btn ghost" onclick="load(${page+1})">Next</button>`:''}</div>`}
function openSong(){ $('form').reset(); $('id').value=''; $('mtitle').textContent='Add song'; $('modal').classList.add('show');}
async function editSong(id){let r=await api('/songs/'+id);if(!r.success)return toast(r.message,'danger');let s=r.data; $('id').value=s.id;$('title').value=s.title||'';$('slug').value=s.slug||'';$('audio_url').value=s.audio_url||'';$('cover_url').value=s.cover_url||'';$('duration_seconds').value=s.duration_seconds||0;$('language').value=s.language||'';$('release_date').value=s.release_date||'';$('description').value=s.description||'';$('lyrics').value=s.lyrics||'';$('is_active').value=s.is_active?'1':'0';$('is_explicit').value=s.is_explicit?'1':'0';$('artists').value=(s.artists||[]).map(a=>a.role&&a.role!=='Main'?a.id+':'+a.role:a.id).join(', ');$('genres').value=(s.genres||[]).map(g=>g.id).join(', ');$('albums').value=(s.albums||[]).map(a=>a.id).join(', ');$('mtitle').textContent='Edit song';$('modal').classList.add('show')}
$('form').onsubmit=async e=>{e.preventDefault();let artists=$('artists').value.split(',').map(x=>x.trim()).filter(Boolean).map(x=>{let [id,...role]=x.split(':');return role.length?{id:Number(id),role:role.join(':')}:Number(id)});let genres=$('genres').value.split(',').map(Number).filter(Boolean);let albums=$('albums').value.split(',').map(x=>Number(x.trim())).filter(Boolean).map(id=>({id}));let body={title:$('title').value,slug:$('slug').value,description:$('description').value,lyrics:$('lyrics').value,audio_url:$('audio_url').value,cover_url:$('cover_url').value,duration_seconds:Number($('duration_seconds').value),language:$('language').value,release_date:$('release_date').value||null,is_explicit:Number($('is_explicit').value),is_active:Number($('is_active').value),artists,genres,albums};let r=await api($('id').value?'/songs/'+$('id').value:'/songs',$('id').value?'PUT':'POST',body);if(r.success){closeModal();toast('Song saved','success');load(page)}else toast(r.message,'danger')};
async function delSong(id){if(!confirm('Delete this song?'))return;let r=await api('/songs/'+id,'DELETE');toast(r.message,r.success?'success':'danger');if(r.success)load(page)}
load();
</script></div></body></html>
